[package]
name = "moosh_id"
version = "0.1.0"
edition = "2024_07"

[lib]
# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html
sierra = true
casm = true

[dependencies]
starknet = "2.11.4"
falcon = { git = "https://github.com/keep-starknet-strange/s2morrow" }
cairo_test = "2.11.4"

[dev-dependencies]
snforge_std = "0.43.1"
assert_macros = "2.11.4"
cairo_execute = "2.11.4"

[[target.starknet-contract]]
sierra = true
casm = true

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]
